//go:build !ignore_autogenerated

/*
Copyright 2026 The scm-metrics-exporter Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoDiscover) DeepCopyInto(out *AutoDiscover) {
	*out = *in
	in.Include.DeepCopyInto(&out.Include)
	in.Exclude.DeepCopyInto(&out.Exclude)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoDiscover.
func (in *AutoDiscover) DeepCopy() *AutoDiscover {
	if in == nil {
		return nil
	}
	out := new(AutoDiscover)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExportConfig) DeepCopyInto(out *ExportConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExportConfig.
func (in *ExportConfig) DeepCopy() *ExportConfig {
	if in == nil {
		return nil
	}
	out := new(ExportConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExporterSpec) DeepCopyInto(out *ExporterSpec) {
	*out = *in
	out.DiscoveryInterval = in.DiscoveryInterval
	in.Resources.DeepCopyInto(&out.Resources)
	out.Export = in.Export
	in.AutoDiscover.DeepCopyInto(&out.AutoDiscover)
	if in.FindingDimensions != nil {
		in, out := &in.FindingDimensions, &out.FindingDimensions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.WorkflowLookback = in.WorkflowLookback
	out.CredentialsSecret = in.CredentialsSecret
	out.ResolutionWindow = in.ResolutionWindow
	if in.Valkey != nil {
		in, out := &in.Valkey, &out.Valkey
		*out = new(ValkeyConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExporterSpec.
func (in *ExporterSpec) DeepCopy() *ExporterSpec {
	if in == nil {
		return nil
	}
	out := new(ExporterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExporterStatus) DeepCopyInto(out *ExporterStatus) {
	*out = *in
	if in.DiscoveredRepositories != nil {
		in, out := &in.DiscoveredRepositories, &out.DiscoveredRepositories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastDiscoveryTime != nil {
		in, out := &in.LastDiscoveryTime, &out.LastDiscoveryTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExporterStatus.
func (in *ExporterStatus) DeepCopy() *ExporterStatus {
	if in == nil {
		return nil
	}
	out := new(ExporterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubMetricsExporter) DeepCopyInto(out *GitHubMetricsExporter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubMetricsExporter.
func (in *GitHubMetricsExporter) DeepCopy() *GitHubMetricsExporter {
	if in == nil {
		return nil
	}
	out := new(GitHubMetricsExporter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubMetricsExporter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubMetricsExporterList) DeepCopyInto(out *GitHubMetricsExporterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GitHubMetricsExporter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubMetricsExporterList.
func (in *GitHubMetricsExporterList) DeepCopy() *GitHubMetricsExporterList {
	if in == nil {
		return nil
	}
	out := new(GitHubMetricsExporterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubMetricsExporterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubMetricsExporterSpec) DeepCopyInto(out *GitHubMetricsExporterSpec) {
	*out = *in
	in.ExporterSpec.DeepCopyInto(&out.ExporterSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubMetricsExporterSpec.
func (in *GitHubMetricsExporterSpec) DeepCopy() *GitHubMetricsExporterSpec {
	if in == nil {
		return nil
	}
	out := new(GitHubMetricsExporterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitLabMetricsExporter) DeepCopyInto(out *GitLabMetricsExporter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitLabMetricsExporter.
func (in *GitLabMetricsExporter) DeepCopy() *GitLabMetricsExporter {
	if in == nil {
		return nil
	}
	out := new(GitLabMetricsExporter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitLabMetricsExporter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitLabMetricsExporterList) DeepCopyInto(out *GitLabMetricsExporterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GitLabMetricsExporter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitLabMetricsExporterList.
func (in *GitLabMetricsExporterList) DeepCopy() *GitLabMetricsExporterList {
	if in == nil {
		return nil
	}
	out := new(GitLabMetricsExporterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitLabMetricsExporterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitLabMetricsExporterSpec) DeepCopyInto(out *GitLabMetricsExporterSpec) {
	*out = *in
	in.ExporterSpec.DeepCopyInto(&out.ExporterSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitLabMetricsExporterSpec.
func (in *GitLabMetricsExporterSpec) DeepCopy() *GitLabMetricsExporterSpec {
	if in == nil {
		return nil
	}
	out := new(GitLabMetricsExporterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoFilter) DeepCopyInto(out *RepoFilter) {
	*out = *in
	if in.Topics != nil {
		in, out := &in.Topics, &out.Topics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Visibility != nil {
		in, out := &in.Visibility, &out.Visibility
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NamePatterns != nil {
		in, out := &in.NamePatterns, &out.NamePatterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Archived != nil {
		in, out := &in.Archived, &out.Archived
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoFilter.
func (in *RepoFilter) DeepCopy() *RepoFilter {
	if in == nil {
		return nil
	}
	out := new(RepoFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValkeyConfig) DeepCopyInto(out *ValkeyConfig) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValkeyConfig.
func (in *ValkeyConfig) DeepCopy() *ValkeyConfig {
	if in == nil {
		return nil
	}
	out := new(ValkeyConfig)
	in.DeepCopyInto(out)
	return out
}
