apiVersion: v1
kind: Service
metadata:
  name: {{ include "scm-metrics-exporter.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scm-metrics-exporter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "scm-metrics-exporter.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.service.port }}
      targetPort: metrics
