apiVersion: v1
kind: Service
metadata:
  name: {{ include "scm-metrics-exporter.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scm-metrics-exporter.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "scm-metrics-exporter.selectorLabels" . | nindent 4 }}
  ports:
    - name: webhook
      port: 443
      targetPort: webhook
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "scm-metrics-exporter.fullname" . }}
  labels:
    {{- include "scm-metrics-exporter.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "scm-metrics-exporter.fullname" . }}-serving-cert
webhooks:
  - name: vgithubmetricsexporter.scm.jalet.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        name: {{ include "scm-metrics-exporter.fullname" . }}-webhook
        namespace: {{ .Release.Namespace }}
        path: /validate-scm-jalet-io-v1alpha1-githubmetricsexporter
    rules:
      - apiGroups: ["scm.jalet.io"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["githubmetricsexporters"]
  - name: vgitlabmetricsexporter.scm.jalet.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        name: {{ include "scm-metrics-exporter.fullname" . }}-webhook
        namespace: {{ .Release.Namespace }}
        path: /validate-scm-jalet-io-v1alpha1-gitlabmetricsexporter
    rules:
      - apiGroups: ["scm.jalet.io"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["gitlabmetricsexporters"]
